import { createRecordHook } from '../../../shared/hooks/useSupabaseRecords.js';
import { DEFAULT_ISSUER_TERMS } from '../../quotes/services/termsTemplateService.js';

export const PDF_TEMPLATE_OPTIONS = [
  { value: 'standard', label: '標準' },
  { value: 'compact', label: 'コンパクト' },
  { value: 'executive', label: 'エグゼクティブ' },
];

export const DEFAULT_ISSUER_TAX_RATE = '8';

export const emptyIssuer = {
  userId: '',
  name: '',
  legalName: '',
  logoUrl: '',
  logoFileName: '',
  logoStoragePath: '',
  address: '',
  phone: '',
  email: '',
  registrationNumber: '',
  bankAccount: '',
  contactPerson: '',
  sealUrl: '',
  sealFileName: '',
  sealStoragePath: '',
  defaultTaxRate: DEFAULT_ISSUER_TAX_RATE,
  defaultPaymentTerms: '',
  defaultDeliveryTerms: '',
  defaultRemarks: '',
  defaultPdfTemplate: 'standard',
  ...DEFAULT_ISSUER_TERMS,
  termsVersion: '',
  termsEffectiveDate: '',
  isDefault: false,
  isActive: true,
  createdAt: '',
  updatedAt: '',
};

export function normalizeIssuer(issuer = {}, userId = '') {
  return {
    ...emptyIssuer,
    ...issuer,
    id: issuer.id ?? crypto.randomUUID(),
    userId: issuer.userId ?? userId,
    name: issuer.name ?? issuer.companyName ?? '',
    legalName: issuer.legalName ?? issuer.legal_name ?? '',
    logoUrl: issuer.logoUrl ?? issuer.logo_url ?? '',
    logoFileName: issuer.logoFileName ?? issuer.logo_file_name ?? '',
    logoStoragePath: issuer.logoStoragePath ?? issuer.logo_storage_path ?? '',
    registrationNumber: issuer.registrationNumber ?? issuer.registration_number ?? '',
    bankAccount: issuer.bankAccount ?? issuer.bank_account ?? '',
    contactPerson: issuer.contactPerson ?? issuer.contact_person ?? '',
    sealUrl: issuer.sealUrl ?? issuer.seal_url ?? '',
    sealFileName: issuer.sealFileName ?? issuer.seal_file_name ?? '',
    sealStoragePath: issuer.sealStoragePath ?? issuer.seal_storage_path ?? '',
    defaultTaxRate: String(issuer.defaultTaxRate ?? issuer.default_tax_rate ?? DEFAULT_ISSUER_TAX_RATE),
    defaultPaymentTerms: issuer.defaultPaymentTerms ?? issuer.default_payment_terms ?? '',
    defaultDeliveryTerms: issuer.defaultDeliveryTerms ?? issuer.default_delivery_terms ?? '',
    defaultRemarks: issuer.defaultRemarks ?? issuer.default_remarks ?? '',
    defaultPdfTemplate: issuer.defaultPdfTemplate ?? issuer.default_pdf_template ?? 'standard',
    defaultTradeTerms: issuer.defaultTradeTerms ?? issuer.default_trade_terms ?? DEFAULT_ISSUER_TERMS.defaultTradeTerms,
    defaultDisclaimer: issuer.defaultDisclaimer ?? issuer.default_disclaimer ?? DEFAULT_ISSUER_TERMS.defaultDisclaimer,
    defaultReturnPolicy: issuer.defaultReturnPolicy ?? issuer.default_return_policy ?? DEFAULT_ISSUER_TERMS.defaultReturnPolicy,
    defaultCancellationPolicy: issuer.defaultCancellationPolicy ?? issuer.default_cancellation_policy ?? DEFAULT_ISSUER_TERMS.defaultCancellationPolicy,
    defaultQualityGuarantee: issuer.defaultQualityGuarantee ?? issuer.default_quality_guarantee ?? DEFAULT_ISSUER_TERMS.defaultQualityGuarantee,
    defaultStorageTerms: issuer.defaultStorageTerms ?? issuer.default_storage_terms ?? DEFAULT_ISSUER_TERMS.defaultStorageTerms,
    defaultDeliveryDisclaimer: issuer.defaultDeliveryDisclaimer ?? issuer.default_delivery_disclaimer ?? DEFAULT_ISSUER_TERMS.defaultDeliveryDisclaimer,
    defaultForceMajeure: issuer.defaultForceMajeure ?? issuer.default_force_majeure ?? DEFAULT_ISSUER_TERMS.defaultForceMajeure,
    defaultPriceRevisionTerms: issuer.defaultPriceRevisionTerms ?? issuer.default_price_revision_terms ?? DEFAULT_ISSUER_TERMS.defaultPriceRevisionTerms,
    defaultConfidentialityTerms: issuer.defaultConfidentialityTerms ?? issuer.default_confidentiality_terms ?? DEFAULT_ISSUER_TERMS.defaultConfidentialityTerms,
    defaultGoverningLaw: issuer.defaultGoverningLaw ?? issuer.default_governing_law ?? DEFAULT_ISSUER_TERMS.defaultGoverningLaw,
    termsVersion: issuer.termsVersion ?? issuer.terms_version ?? '',
    termsEffectiveDate: issuer.termsEffectiveDate ?? issuer.terms_effective_date ?? '',
    isDefault: Boolean(issuer.isDefault ?? issuer.is_default ?? false),
    isActive: issuer.isActive ?? issuer.is_active ?? true,
    createdAt: issuer.createdAt ?? issuer.created_at ?? new Date().toISOString(),
    updatedAt: issuer.updatedAt ?? issuer.updated_at ?? new Date().toISOString(),
  };
}

export function createIssuerSnapshot(issuer = null) {
  if (!issuer) return null;
  const normalized = normalizeIssuer(issuer, issuer.userId);
  return {
    id: normalized.id,
    name: normalized.name,
    legalName: normalized.legalName,
    logoUrl: normalized.logoUrl,
    address: normalized.address,
    phone: normalized.phone,
    email: normalized.email,
    registrationNumber: normalized.registrationNumber,
    bankAccount: normalized.bankAccount,
    contactPerson: normalized.contactPerson,
    sealUrl: normalized.sealUrl,
    defaultTaxRate: normalized.defaultTaxRate,
    defaultPaymentTerms: normalized.defaultPaymentTerms,
    defaultDeliveryTerms: normalized.defaultDeliveryTerms,
    defaultRemarks: normalized.defaultRemarks,
    defaultPdfTemplate: normalized.defaultPdfTemplate,
    defaultTradeTerms: normalized.defaultTradeTerms,
    defaultDisclaimer: normalized.defaultDisclaimer,
    defaultReturnPolicy: normalized.defaultReturnPolicy,
    defaultCancellationPolicy: normalized.defaultCancellationPolicy,
    defaultQualityGuarantee: normalized.defaultQualityGuarantee,
    defaultStorageTerms: normalized.defaultStorageTerms,
    defaultDeliveryDisclaimer: normalized.defaultDeliveryDisclaimer,
    defaultForceMajeure: normalized.defaultForceMajeure,
    defaultPriceRevisionTerms: normalized.defaultPriceRevisionTerms,
    defaultConfidentialityTerms: normalized.defaultConfidentialityTerms,
    defaultGoverningLaw: normalized.defaultGoverningLaw,
    termsVersion: normalized.termsVersion,
    termsEffectiveDate: normalized.termsEffectiveDate,
    snapshotCreatedAt: new Date().toISOString(),
  };
}

function toRow(issuer) {
  return {
    id: issuer.id,
    user_id: issuer.userId,
    name: issuer.name,
    legal_name: issuer.legalName,
    logo_url: issuer.logoUrl,
    logo_file_name: issuer.logoFileName,
    logo_storage_path: issuer.logoStoragePath,
    address: issuer.address,
    phone: issuer.phone,
    email: issuer.email,
    registration_number: issuer.registrationNumber,
    bank_account: issuer.bankAccount,
    contact_person: issuer.contactPerson,
    seal_url: issuer.sealUrl,
    seal_file_name: issuer.sealFileName,
    seal_storage_path: issuer.sealStoragePath,
    default_tax_rate: issuer.defaultTaxRate === '' ? null : Number(issuer.defaultTaxRate),
    default_payment_terms: issuer.defaultPaymentTerms,
    default_delivery_terms: issuer.defaultDeliveryTerms,
    default_remarks: issuer.defaultRemarks,
    default_pdf_template: issuer.defaultPdfTemplate,
    default_trade_terms: issuer.defaultTradeTerms,
    default_disclaimer: issuer.defaultDisclaimer,
    default_return_policy: issuer.defaultReturnPolicy,
    default_cancellation_policy: issuer.defaultCancellationPolicy,
    default_quality_guarantee: issuer.defaultQualityGuarantee,
    default_storage_terms: issuer.defaultStorageTerms,
    default_delivery_disclaimer: issuer.defaultDeliveryDisclaimer,
    default_force_majeure: issuer.defaultForceMajeure,
    default_price_revision_terms: issuer.defaultPriceRevisionTerms,
    default_confidentiality_terms: issuer.defaultConfidentialityTerms,
    default_governing_law: issuer.defaultGoverningLaw,
    terms_version: issuer.termsVersion,
    terms_effective_date: issuer.termsEffectiveDate || null,
    is_default: issuer.isDefault,
    is_active: issuer.isActive,
    created_at: issuer.createdAt,
    updated_at: issuer.updatedAt,
  };
}

function fromRow(row) {
  return normalizeIssuer({
    id: row.id,
    userId: row.user_id,
    name: row.name,
    legalName: row.legal_name,
    logoUrl: row.logo_url,
    logoFileName: row.logo_file_name,
    logoStoragePath: row.logo_storage_path,
    address: row.address,
    phone: row.phone,
    email: row.email,
    registrationNumber: row.registration_number,
    bankAccount: row.bank_account,
    contactPerson: row.contact_person,
    sealUrl: row.seal_url,
    sealFileName: row.seal_file_name,
    sealStoragePath: row.seal_storage_path,
    defaultTaxRate: row.default_tax_rate ?? DEFAULT_ISSUER_TAX_RATE,
    defaultPaymentTerms: row.default_payment_terms,
    defaultDeliveryTerms: row.default_delivery_terms,
    defaultRemarks: row.default_remarks,
    defaultPdfTemplate: row.default_pdf_template,
    defaultTradeTerms: row.default_trade_terms,
    defaultDisclaimer: row.default_disclaimer,
    defaultReturnPolicy: row.default_return_policy,
    defaultCancellationPolicy: row.default_cancellation_policy,
    defaultQualityGuarantee: row.default_quality_guarantee,
    defaultStorageTerms: row.default_storage_terms,
    defaultDeliveryDisclaimer: row.default_delivery_disclaimer,
    defaultForceMajeure: row.default_force_majeure,
    defaultPriceRevisionTerms: row.default_price_revision_terms,
    defaultConfidentialityTerms: row.default_confidentiality_terms,
    defaultGoverningLaw: row.default_governing_law,
    termsVersion: row.terms_version,
    termsEffectiveDate: row.terms_effective_date,
    isDefault: row.is_default,
    isActive: row.is_active,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  });
}

export const useIssuers = createRecordHook({
  tableName: 'issuers',
  storageKey: 'eigyo-techo-issuers',
  normalize: normalizeIssuer,
  toRow,
  fromRow,
});
