const DEFAULT_TABLE_CONFIG = {
  orderColumn: 'updated_at',
  realtime: false,
  audit: true,
  softDelete: false,
  localPersistence: false,
  returnWritePromise: false,
  searchable: [],
  defaultSort: { key: 'updatedAt', direction: 'desc' },
  displayName: 'Record',
};

export const TABLE_CONFIG = {
  customers: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['customer_code', 'company_name', 'company_kana', 'industry', 'area', 'tags', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u53d6\u5f15\u5148',
  },
  products: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    returnWritePromise: true,
    searchable: ['product_code', 'name', 'brand_name', 'category', 'manufacturer_name', 'origin', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u5546\u54c1',
  },
  brands: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    returnWritePromise: true,
    searchable: ['name', 'country', 'description', 'website_url'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: 'Brand',
  },
  product_assets: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: false,
    returnWritePromise: true,
    searchable: ['file_name', 'description', 'asset_kind', 'asset_type'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: 'Product Asset',
  },
  quotes: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['quote_number', 'project_name', 'status', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u898b\u7a4d',
  },
  orders: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['order_number', 'sales_order_number', 'title', 'status'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u53d7\u6ce8',
  },
  sales_orders: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['order_number', 'sales_order_number', 'title', 'status'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u53d7\u6ce8',
  },
  deliveries: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['delivery_note_number', 'status'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u7d0d\u54c1\u66f8',
  },
  delivery_notes: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['delivery_note_number', 'status'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u7d0d\u54c1\u66f8',
  },
  issuers: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: false,
    returnWritePromise: true,
    searchable: ['name', 'legal_name', 'registration_number', 'contact_person', 'bank_account'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: 'Issuer',
  },
  inventory: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['inventory_code', 'lot', 'owner', 'location', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u5728\u5eab',
  },
  inventories: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['inventory_code', 'lot', 'owner', 'location', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u5728\u5eab',
  },
  inventory_movements: {
    orderColumn: 'created_at',
    realtime: true,
    audit: true,
    softDelete: false,
    searchable: ['movement_type', 'reason', 'lot', 'memo'],
    defaultSort: { key: 'createdAt', direction: 'desc' },
    displayName: '\u5165\u51fa\u5eab\u5c65\u6b74',
  },
  inbound_shipments: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['source_file_name', 'document_number', 'supplier_name', 'status'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u5165\u8377\u4e88\u5b9a',
  },
  inbound_shipment_lines: {
    orderColumn: 'line_no',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['contract_no', 'brand_name_raw', 'product_name_raw', 'warehouse_name', 'match_status'],
    defaultSort: { key: 'lineNo', direction: 'asc' },
    displayName: '\u5165\u8377\u4e88\u5b9a\u660e\u7d30',
  },
  supplier_product_aliases: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: false,
    searchable: ['supplier_name', 'alias_name', 'brand_name', 'factory_no', 'origin_country'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u4ed5\u5165\u5148\u5546\u54c1\u5225\u540d',
  },
  customer_product_prices: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['price_type', 'memo', 'change_reason'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u9867\u5ba2\u5225\u4fa1\u683c',
  },
  customer_product_price_history: {
    orderColumn: 'created_at',
    realtime: true,
    audit: true,
    softDelete: false,
    searchable: ['change_type', 'reason', 'price_type'],
    defaultSort: { key: 'createdAt', direction: 'desc' },
    displayName: '\u4fa1\u683c\u5c65\u6b74',
  },
  events: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    returnWritePromise: true,
    searchable: ['title', 'event_type', 'location', 'memo'],
    defaultSort: { key: 'startAt', direction: 'asc' },
    displayName: '\u4e88\u5b9a',
  },
  tasks: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    returnWritePromise: true,
    searchable: ['title', 'content', 'status', 'priority', 'assignee_name'],
    defaultSort: { key: 'dueDate', direction: 'asc' },
    displayName: '\u30bf\u30b9\u30af',
  },
  suppliers: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['name', 'country', 'supplier_type', 'contact_person', 'email', 'products', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u4ed5\u5165\u5148',
  },
  complaints: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['type', 'content', 'status', 'cause', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u30af\u30ec\u30fc\u30e0',
  },
  contacts: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['name', 'department', 'position', 'email', 'phone', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u62c5\u5f53\u8005',
  },
  business_cards: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['name', 'company_name', 'department', 'position', 'email'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '\u540d\u523a',
  },
};

export function getTableConfig(tableName) {
  return {
    ...DEFAULT_TABLE_CONFIG,
    ...(TABLE_CONFIG[tableName] ?? {}),
  };
}

export function getTableOrderColumn(tableName, fallback = '') {
  return getTableConfig(tableName).orderColumn || fallback || DEFAULT_TABLE_CONFIG.orderColumn;
}
