const DEFAULT_TABLE_CONFIG = {
  orderColumn: 'updated_at',
  realtime: false,
  audit: true,
  softDelete: false,
  searchable: [],
  defaultSort: { key: 'updatedAt', direction: 'desc' },
  displayName: 'Record',
};

export const TABLE_CONFIG = {
  customers: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['customer_code', 'company_name', 'company_kana', 'industry', 'area', 'tags', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '取引先',
  },
  products: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    disableLocalPersistence: true,
    searchable: ['product_code', 'name', 'brand_name', 'category', 'manufacturer_name', 'origin', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '商品',
  },
  brands: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    disableLocalPersistence: true,
    searchable: ['name', 'country', 'description', 'website_url'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: 'Brand',
  },
  product_assets: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: false,
    disableLocalPersistence: true,
    searchable: ['file_name', 'description', 'asset_kind', 'asset_type'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: 'Product Asset',
  },
  quotes: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['quote_number', 'project_name', 'status', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '見積',
  },
  orders: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['order_number', 'sales_order_number', 'title', 'status'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '受注',
  },
  sales_orders: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['order_number', 'sales_order_number', 'title', 'status'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '受注',
  },
  deliveries: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['delivery_note_number', 'status'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '納品書',
  },
  delivery_notes: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['delivery_note_number', 'status'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '納品書',
  },
  inventory: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['inventory_code', 'lot', 'owner', 'location', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '在庫',
  },
  inventories: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['inventory_code', 'lot', 'owner', 'location', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '在庫',
  },
  inventory_movements: {
    orderColumn: 'created_at',
    realtime: true,
    audit: true,
    softDelete: false,
    searchable: ['movement_type', 'reason', 'lot', 'memo'],
    defaultSort: { key: 'createdAt', direction: 'desc' },
    displayName: '入出庫履歴',
  },
  customer_product_prices: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['price_type', 'memo', 'change_reason'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '顧客別価格',
  },
  customer_product_price_history: {
    orderColumn: 'created_at',
    realtime: true,
    audit: true,
    softDelete: false,
    searchable: ['change_type', 'reason', 'price_type'],
    defaultSort: { key: 'createdAt', direction: 'desc' },
    displayName: '価格履歴',
  },
  events: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    disableLocalPersistence: true,
    searchable: ['title', 'event_type', 'location', 'memo'],
    defaultSort: { key: 'startAt', direction: 'asc' },
    displayName: '予定',
  },
  tasks: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    disableLocalPersistence: true,
    searchable: ['title', 'content', 'status', 'priority', 'assignee_name'],
    defaultSort: { key: 'dueDate', direction: 'asc' },
    displayName: 'タスク',
  },
  suppliers: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['name', 'country', 'supplier_type', 'contact_person', 'email', 'products', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '仕入先',
  },
  complaints: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['type', 'content', 'status', 'cause', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: 'クレーム',
  },
  contacts: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['name', 'department', 'position', 'email', 'phone', 'memo'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '担当者',
  },
  business_cards: {
    orderColumn: 'updated_at',
    realtime: true,
    audit: true,
    softDelete: true,
    searchable: ['name', 'company_name', 'department', 'position', 'email'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    displayName: '名刺',
  },
};

export function getTableConfig(tableName) {
  return {
    ...DEFAULT_TABLE_CONFIG,
    ...(TABLE_CONFIG[tableName] ?? {}),
  };
}

export function getTableOrderColumn(tableName, fallback = '') {
  return getTableConfig(tableName).orderColumn || fallback || DEFAULT_TABLE_CONFIG.orderColumn;
}
